<a href="https://colab.research.google.com/github/kothapallysidhartha/APPLICATIONS-OF-DATAMINING/blob/main/assignment1_AD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tasks:
# 1.	Load the dataset using Pandas. **bold text**

In [1]:
import pandas as pd
file_path = "student-dataset.csv"
df = pd.read_csv(file_path)

In [2]:
df

,id,name,nationality,city,latitude,longitude,gender,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,22,3.5,3.7,3.1,1.0,4,4.0,4
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,22,2.9,3.2,3.6,5.0,5,4.0,5
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,22,3.9,3.8,3.2,5.0,3,3.0,4
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,20,3.3,2.8,NaN,5.0,5,2.0,4
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,21,3.7,2.6,3.4,1.0,4,4.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,302,Austin Haas,United States of America,Columbus,39.96,-83.00,M,20,3.6,3.7,3.1,5.0,4,5.0,5
303,303,Madison Fithian,United States of America,Los Angeles,34.05,-118.24,F,20,3.6,3.9,4.0,5.0,5,5.0,3
304,304,Zachary Mulvahill,United States of America,Los Angeles,34.05,-118.24,M,20,3.2,3.4,3.9,5.0,5,5.0,3
305,305,Eliana Michelsen,United States of America,Oakland,37.80,-122.27,F,23,3.0,2.8,2.9,5.0,4,4.0,5
306,306,Dane Whittemore,Canada,Toronto,43.67,-79.42,M,21,3.8,3.2,4.0,5.0,5,4.0,5

# **	Fill missing science scores using median imputation.**

In [3]:
df.isnull()

,id,name,nationality,city,latitude,longitude,gender,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
303,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
304,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
305,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
306,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [4]:

print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
id                    0
name                  0
nationality           0
city                  0
latitude              0
longitude             0
gender                0
age                   0
english.grade         0
math.grade            0
sciences.grade        9
language.grade        0
portfolio.rating      0
coverletter.rating    0
refletter.rating      0
dtype: int64

In [5]:
from sklearn.preprocessing import MinMaxScaler

In [6]:
sciences_median = df['sciences.grade'].median()
df['sciences.grade'].fillna(sciences_median, inplace=True)

<ipython-input-6-f499c018b121>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sciences.grade'].fillna(sciences_median, inplace=True)

# **Columns for which we need to perform Normalization**

In [10]:
exam_columns = ['english.grade', 'math.grade', 'sciences.grade', 'language.grade']

In [11]:
scaler = MinMaxScaler()
df[exam_columns] = scaler.fit_transform(df[exam_columns])

In [12]:
df[exam_columns]

     english.grade  math.grade  sciences.grade  language.grade
0             0.80    0.842105        0.653846             0.0
1             0.56    0.578947        0.846154             1.0
2             0.96    0.894737        0.692308             1.0
3             0.72    0.368421        0.846154             1.0
4             0.88    0.263158        0.769231             0.0
..             ...         ...             ...             ...
302           0.84    0.842105        0.653846             1.0
303           0.84    0.947368        1.000000             1.0
304           0.68    0.684211        0.961538             1.0
305           0.60    0.368421        0.576923             1.0
306           0.92    0.578947        1.000000             1.0

[307 rows x 4 columns]

In [13]:
df.to_csv("updated_student_dataset.csv", index=False)

In [14]:
print("Updated dataset preview:")
print(df.head())

Updated dataset preview:
   id             name               nationality                 city  \
0   0        Kiana Lor                     China               Suzhou
1   1   Joshua Lonaker  United States of America        Santa Clarita
2   2    Dakota Blanco  United States of America              Oakland
3   3  Natasha Yarusso  United States of America        Castro Valley
4   4   Brooke Cazares                    Brazil  São José dos Campos

   latitude  longitude gender  age  english.grade  math.grade  sciences.grade  \
0     31.31     120.62      F   22           0.80    0.842105        0.653846
1     34.39    -118.54      M   22           0.56    0.578947        0.846154
2     37.80    -122.27      F   22           0.96    0.894737        0.692308
3     37.69    -122.09      F   20           0.72    0.368421        0.846154
4    -23.18     -45.88      F   21           0.88    0.263158        0.769231

   language.grade  portfolio.rating  coverletter.rating  refletter.rating
0             0.0                 4                 4.0                 4
1             1.0                 5                 4.0                 5
2             1.0                 3                 3.0                 4
3             1.0                 5                 2.0                 4
4             0.0                 4                 4.0                 5